name: Conduit-actions
on: [push, workflow_dispatch]
jobs:
  run_linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v6.5.1  
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    runs-on: ubuntu-latest
    needs: run_linter
    steps: 
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # - name: Build backend
      #   working-directory: ./backend
      #   run: npm run build

      # - name: Test app
      #   run: npm start

